(()=>{'use strict';
const MAIN_VERSION='0.12.15',CORE_VERSION='0.12.10';
const MAIN_BASE=`https://cdn.jsdelivr.net/npm/@ffmpeg/ffmpeg@${MAIN_VERSION}/dist/umd`;
const CORE_BASE=`https://cdn.jsdelivr.net/npm/@ffmpeg/core@${CORE_VERSION}/dist/umd`;
const $=id=>document.getElementById(id);
const e={loadBtn:$('loadBtn'),fileInput:$('fileInput'),dropZone:$('dropZone'),fileInfo:$('fileInfo'),fileName:$('fileName'),fileSize:$('fileSize'),fileType:$('fileType'),format:$('format'),quality:$('quality'),resolution:$('resolution'),audioRate:$('audioRate'),trimStart:$('trimStart'),trimEnd:$('trimEnd'),mute:$('mute'),fastMode:$('fastMode'),extraArgs:$('extraArgs'),convertBtn:$('convertBtn'),cancelBtn:$('cancelBtn'),progressBar:$('progressBar'),progressLabel:$('progressLabel'),progressPct:$('progressPct'),resultBox:$('resultBox'),resultMeta:$('resultMeta'),downloadBtn:$('downloadBtn'),videoPreview:$('videoPreview'),audioPreview:$('audioPreview'),imagePreview:$('imagePreview'),log:$('log'),clearLog:$('clearLog'),statusDot:$('statusDot'),statusText:$('statusText'),localWarning:$('localWarning')};
let ffmpeg=null,file=null,loaded=false,busy=false,outURL=null,outBlob=null,outName='',blobURLs=[];
if(location.protocol==='file:')e.localWarning.classList.remove('hidden');
function log(m){const t=new Date().toLocaleTimeString();if(e.log.textContent.startsWith('Ready.'))e.log.textContent='';e.log.textContent+=`[${t}] ${m}\n`;e.log.scrollTop=e.log.scrollHeight}
function status(t,c=''){e.statusText.textContent=t;e.statusDot.className=c}
function size(n){const u=['B','KB','MB','GB','TB'];let i=0,v=n;while(v>=1024&&i<u.length-1){v/=1024;i++}return`${i?v.toFixed(1):v.toFixed(0)} ${u[i]}`}
function refresh(){e.convertBtn.disabled=!(loaded&&file&&!busy);e.cancelBtn.disabled=!busy}
function clearResult(){e.resultBox.classList.add('hidden');for(const x of[e.videoPreview,e.audioPreview,e.imagePreview]){x.classList.add('hidden');x.removeAttribute('src')}if(outURL){URL.revokeObjectURL(outURL);outURL=null}outBlob=null;outName=''}
async function textBlob(url,transform){const r=await fetch(url,{cache:'force-cache'});if(!r.ok)throw new Error(`Download failed (${r.status}): ${url}`);let s=await r.text();if(transform)s=transform(s);const u=URL.createObjectURL(new Blob([s],{type:'text/javascript'}));blobURLs.push(u);return u}
async function binBlob(url){const r=await fetch(url,{cache:'force-cache'});if(!r.ok)throw new Error(`Download failed (${r.status}): ${url}`);const u=URL.createObjectURL(new Blob([await r.arrayBuffer()],{type:'application/wasm'}));blobURLs.push(u);return u}
function patchMainWorker(js){const a='new URL(e.p+e.u(814),e.b)',b='new URL(e.p + e.u(814), e.b)';if(js.includes(a))return js.replace(a,'r.workerLoadURL');if(js.includes(b))return js.replace(b,'r.workerLoadURL');throw new Error('FFmpeg loader layout changed. Runtime versions need updating.')}
async function loadEngine(){if(loaded||busy)return;e.loadBtn.disabled=true;status('Loading engine…','busy');log(`Loading ffmpeg.wasm ${MAIN_VERSION} and FFmpeg core ${CORE_VERSION}…`);try{if(!globalThis.FFmpegWASM){const main=await textBlob(`${MAIN_BASE}/ffmpeg.js`,patchMainWorker);await import(main)}if(!globalThis.FFmpegWASM?.FFmpeg)throw new Error('FFmpegWASM did not initialize');const workerLoadURL=await textBlob(`${MAIN_BASE}/814.ffmpeg.js`);const coreURL=await textBlob(`${CORE_BASE}/ffmpeg-core.js`);const wasmURL=await binBlob(`${CORE_BASE}/ffmpeg-core.wasm`);ffmpeg=new globalThis.FFmpegWASM.FFmpeg();ffmpeg.on('log',({message})=>{if(message)log(message)});ffmpeg.on('progress',({progress,time})=>{if(!busy)return;const p=Math.max(0,Math.min(100,Math.round((progress||0)*100)));e.progressBar.style.width=p+'%';e.progressPct.textContent=p+'%';e.progressLabel.textContent=time>0?`Encoded ${(time/1000000).toFixed(1)} sec`:'Converting…'});await ffmpeg.load({workerLoadURL,coreURL,wasmURL});loaded=true;status('Engine ready','ok');e.loadBtn.textContent='Engine Loaded';log('FFmpeg engine ready.');refresh()}catch(err){console.error(err);ffmpeg=null;loaded=false;status('Engine load failed','err');e.loadBtn.disabled=false;e.loadBtn.textContent='Retry Engine';log('ERROR: '+(err?.message||err));log('If you opened index.html directly, use GitHub Pages instead.')}}
function chooseFile(f){if(!f)return;file=f;e.fileName.textContent=f.name;e.fileSize.textContent=size(f.size);e.fileType.textContent=f.type||'media file';e.fileInfo.classList.remove('hidden');clearResult();if(f.size>1024*1024*1024)log('Warning: files over 1 GB may exceed browser memory limits.');log(`Selected ${f.name} (${size(f.size)})`);refresh()}
function splitArgs(s){const out=[];let cur='',q=null;for(let i=0;i<s.length;i++){const c=s[i];if(q){if(c===q)q=null;else if(c==='\\'&&i+1<s.length)cur+=s[++i];else cur+=c}else if(c==='"'||c==="'")q=c;else if(/\s/.test(c)){if(cur){out.push(cur);cur=''}}else cur+=c}if(cur)out.push(cur);return out}
function filters(fmt){const h=e.resolution.value;if(['mp3','wav','flac'].includes(fmt))return[];if(fmt==='gif'){const sc=h==='original'?'scale=iw:ih:flags=lanczos':`scale=-2:${h}:flags=lanczos`;return['-vf',`fps=12,${sc}`]}if(h==='original')return[];return['-vf',`scale=-2:'min(${h},ih)'`]}
function codecs(fmt){const q=e.quality.value,a=`${e.audioRate.value}k`,fast=e.fastMode.checked,crf=q==='high'?'19':q==='small'?'28':'23',vp9=q==='high'?'27':q==='small'?'39':'32',preset=fast?'ultrafast':'veryfast';if(fmt==='mp3')return['-vn','-c:a','libmp3lame','-b:a',a];if(fmt==='wav')return['-vn','-c:a','pcm_s16le'];if(fmt==='flac')return['-vn','-c:a','flac'];if(fmt==='gif')return[];let x=[];if(fmt==='webm')x.push('-c:v','libvpx-vp9','-crf',vp9,'-b:v','0','-cpu-used',fast?'5':'3');else x.push('-c:v','libx264','-preset',preset,'-crf',crf,'-pix_fmt','yuv420p');if(fmt==='mp4')x.push('-movflags','+faststart');if(!e.mute.checked)x.push('-c:a',fmt==='webm'?'libopus':'aac','-b:a',a);return x}
function mime(fmt){return({mp4:'video/mp4',mkv:'video/x-matroska',webm:'video/webm',mov:'video/quicktime',mp3:'audio/mpeg',wav:'audio/wav',flac:'audio/flac',gif:'image/gif'})[fmt]||'application/octet-stream'}
async function convert(){if(!loaded||!ffmpeg||!file||busy)return;clearResult();busy=true;refresh();status('Converting…','busy');e.progressBar.style.width='0%';e.progressPct.textContent='0%';e.progressLabel.textContent='Preparing input…';const fmt=e.format.value,ext=(file.name.match(/\.([^.]+)$/)?.[1]||'bin').replace(/[^a-z0-9]/gi,'').toLowerCase(),inName='input.'+ext,tmp='output.'+fmt;try{await ffmpeg.writeFile(inName,new Uint8Array(await file.arrayBuffer()));let args=['-i',inName];if(e.trimStart.value.trim())args.push('-ss',e.trimStart.value.trim());if(e.trimEnd.value.trim())args.push('-to',e.trimEnd.value.trim());args.push(...filters(fmt));if(e.mute.checked&&!['mp3','wav','flac'].includes(fmt))args.push('-an');args.push(...codecs(fmt));if(e.extraArgs.value.trim())args.push(...splitArgs(e.extraArgs.value));args.push(tmp);log('ffmpeg '+args.map(x=>/\s/.test(x)?`"${x}"`:x).join(' '));const rc=await ffmpeg.exec(args);if(rc!==0)throw new Error('FFmpeg exited with code '+rc);const data=await ffmpeg.readFile(tmp);outBlob=new Blob([data.buffer],{type:mime(fmt)});outURL=URL.createObjectURL(outBlob);const stem=file.name.replace(/\.[^.]+$/,'')||'converted';outName=`${stem}_converted.${fmt}`;e.resultMeta.textContent=`${outName} · ${size(outBlob.size)}`;e.resultBox.classList.remove('hidden');if(fmt==='gif'){e.imagePreview.src=outURL;e.imagePreview.classList.remove('hidden')}else if(['mp3','wav','flac'].includes(fmt)){e.audioPreview.src=outURL;e.audioPreview.classList.remove('hidden')}else{e.videoPreview.src=outURL;e.videoPreview.classList.remove('hidden')}e.progressBar.style.width='100%';e.progressPct.textContent='100%';e.progressLabel.textContent='Complete';status('Conversion complete','ok');log(`Complete: ${outName} (${size(outBlob.size)})`);try{await ffmpeg.deleteFile(inName);await ffmpeg.deleteFile(tmp)}catch(_){}}catch(err){status('Conversion failed','err');log('ERROR: '+(err?.message||err))}finally{busy=false;refresh()}}
function cancel(){if(!busy||!ffmpeg)return;log('Cancel requested. Terminating worker…');try{ffmpeg.terminate()}catch(_){}ffmpeg=null;loaded=false;busy=false;e.loadBtn.disabled=false;e.loadBtn.textContent='Reload Engine';e.progressLabel.textContent='Canceled';status('Engine stopped','err');refresh()}
e.loadBtn.addEventListener('click',loadEngine);e.fileInput.addEventListener('change',x=>chooseFile(x.target.files?.[0]));['dragenter','dragover'].forEach(n=>e.dropZone.addEventListener(n,x=>{x.preventDefault();e.dropZone.classList.add('over')}));['dragleave','drop'].forEach(n=>e.dropZone.addEventListener(n,x=>{x.preventDefault();e.dropZone.classList.remove('over')}));e.dropZone.addEventListener('drop',x=>chooseFile(x.dataTransfer.files?.[0]));e.convertBtn.addEventListener('click',convert);e.cancelBtn.addEventListener('click',cancel);e.downloadBtn.addEventListener('click',()=>{if(!outURL)return;const a=document.createElement('a');a.href=outURL;a.download=outName;a.click()});e.clearLog.addEventListener('click',()=>e.log.textContent='');e.format.addEventListener('change',()=>{const a=['mp3','wav','flac'].includes(e.format.value);e.resolution.disabled=a;e.mute.disabled=a;e.quality.disabled=['wav','flac'].includes(e.format.value)});refresh();
})();
